### ISSUE TITLE
Enable strict null checks

### ISSUE THREAD

**Issue by iorlandini** [openunite/openunite#30]
I saw `getUser(): User | null { }` in the code. But this doesn't make sense unless we enable strict null checks. I propose to enable it!

**Comment by alanreid** [comment]
It's already enabled with the `strict: true` key in `web/tsconfig.json`

Enabling `--strict` enables:

```
--noImplicitAny
--noImplicitThis
--alwaysStrict
--strictBindCallApply
--strictNullChecks
--strictFunctionTypes 
--strictPropertyInitialization
```

**Comment by iorlandini** [comment]
Excellent. I didn't realize.
